# Generated by Django 5.0.6 on 2024-06-25 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0002_rename_user_todo_peoples'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='peoples',
            new_name='user',
        ),
    ]
